apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nomios.fullname" . }}
  labels:
    app: {{ template "nomios.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: {{ .Values.event.type }}
    kind: {{ .Values.event.kind }}
data:
  config.json: |
    {
      "type": "registry",
      "kind": "dockerhub",
      "service-url": "http://{{ template "nomios.fullname" . }}:{{ .Values.service.externalPort }}",
      "uri-template": "index.docker.io:{{"{{"}}repo-owner{{"}}"}}:{{"{{"}}repo-name{{"}}"}}:push",
      "uri-regex": "^index\\.docker\\.io:[a-z0-9_-]+:[a-z0-9_-]+:push$",
      "config": [{
              "name": "repo-owner",
              "type": "string",
              "validator": "^[A-z0-9]+$",
              "required": true
          },
          {
              "name": "repo-name",
              "type": "string",
              "validator": "^[A-z0-9]+$",
              "required": true
          }
      ]
    }